
name = "DashSortableTree"
uuid = "1b08a953-4be3-4667-9a23-a0306b7ffa84"
authors = ["Marian Stefanescu <marianstefi20@gmail.com>"]
version = "0.0.7"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
